<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Actions' => 'Acțiuni',
    'Active' => 'Activ',
    'Add Book' => 'Adaugă Carte',
    'All' => 'Toate',
    'Are you sure to delete this item?' => 'Sunteți sigur(ă) că vreți să ștergeți acest obiect?',
    'Book Listing' => 'Listă cărți',
    'CSV' => 'CSV',
    'Clear selection' => 'Anulează selecția',
    'Collapse All' => 'Restrânge Toate',
    'Collapse' => 'Restrânge',
    'Comma Separated Values' => 'Valori separate prin virgulă',
    'Delete' => 'Șterge',
    'Disable any popup lockers in your browser to ensure proper download.' => 'Dezactivează orice blocare de pop-up-uri în navigatorul dumneavoastră pentru a asigura descărcarea.',
    'Download Selected' => 'Descarcă Selectate',
    'Excel' => 'Excel',
    'Expand All' => 'Destinde Toate',
    'Expand' => 'Destinde',
    'Export All Data' => 'Exportă toate datele',
    'Export Page Data' => 'Exportă datele paginii',
    'Export' => 'Export',
    'ExportWorksheet' => 'Exportă pagina de lucru',
    'Generated' => 'Generat',
    'Generating the export file. Please wait...' => 'S-a generat fișierul de export. Vă rugăm așteptați...',
    'Grid Export' => 'Export Grilă',
    'HTML' => 'HTML',
    'Hyper Text Markup Language' => 'Hyper Text Markup Language',
    'Inactive' => 'Inactiv',
    'Invalid editable index or model form name' => 'Index editabil sau numele formularului de model invalide',
    'Invalid or bad editable data' => 'Invalid sau date editabile rele',
    'JSON' => 'JSON',
    'JavaScript Object Notation' => 'JavaScript Object Notation',
    'Library' => 'Bibliotecă',
    'Microsoft Excel 95+' => 'Microsoft Excel 95+',
    'No data found' => 'N-au fost găsite date',
    'No valid editable model found' => 'N-a fost găsit model editabil valid',
    'Ok to proceed?' => 'Se poate proceda?',
    'PDF export generated by kartik-v/yii2-grid extension' => 'Fișiere PDF exportat de extensia kartik-v/yii2-grid',
    'PDF' => 'PDF',
    'Page' => 'Pagină',
    'Portable Document Format' => 'Portable Document Format',
    'Request submitted! You may safely close this dialog after saving your downloaded file.' => 'Cerere trimisă! Acum puteți închide această fereastră de dialog după ce se descarcă fișierul.',
    'Reset Grid' => 'Resetează grilă',
    'Resize table columns just like a spreadsheet by dragging the column edges.' => 'Coloane ajustabile de tabel prin tragere de margini, tocmai ca la foaie de lucru.',
    'Show all data' => 'Arată toate datele',
    'Show first page data' => 'Arată prima pagină de date',
    'Tab Delimited Text' => 'Text delimitat prin tab',
    'Text' => 'Text',
    'The CSV export file will be generated for download.' => 'Fișierul de export CSV a fost generat pentru descărcare',
    'The EXCEL export file will be generated for download.' => 'Fișierul de export EXCEL a fost generat pentru descărcare',
    'The HTML export file will be generated for download.' => 'Fișierul de export HTML a fost generat pentru descărcare',
    'The JSON export file will be generated for download.' => 'Fișierul de export JSON a fost generat pentru descărcare',
    'The PDF export file will be generated for download.' => 'Fișierul de export PDF a fost generat pentru descărcare',
    'The TEXT export file will be generated for download.' => 'Fișierul de export TEXT a fost generat pentru descărcare',
    'The page summary displays SUM for first 3 amount columns and AVG for the last.' => 'Sumarul paginii afișează suma pentru primele 3 coloane și media pentru ultima',
    'The table header sticks to the top in this demo as you scroll' => 'Capul tabelului rămâne sus în timp ce derulați pagina în jos',
    'There are {totalCount} records. Are you sure you want to display them all?' => 'Sunt {totalCount} înregistrări. Sunteți sigur(ă) că vreți să le afișați pe toate?',
    'Update' => 'Actualizează',
    'View' => 'Afișează',
    'Yii2 Grid Export (PDF)' => 'Export grilă Yii2 (PDF)',
    'export' => 'export',
    'grid-export' => 'grid-export',
    'krajee, grid, export, yii2-grid, pdf' => 'krajee, grid, export, yii2-grid, pdf',
    '© Krajee Yii2 Extensions' => '© Krajee Yii2 Extensions',
];
    
